# Generated by Django 5.2.1 on 2025-05-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'CC'), ('Pasaporte', 'Pasaporte'), ('Otro', 'Otro')], max_length=20, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
